### ISSUE TITLE
Missing BaseBanner on sample app

### ISSUE THREAD

**Issue by ararog** [H07000223/FlycoPageIndicator#4]
I'm porting the library to Xamarin, but I can't find the BaseBanner class used by the sample app,
can you please commit BaseBanner source file? 

Thanks!

**Comment by H07000223** [comment]
https://github.com/H07000223/FlycoBanner_Master

**Comment by ararog** [comment]
I ended up by creating another example which doesn't require FlycoBanner.

Btw, here's the Xamarin port https://github.com/ararog/FlycoPageIndicator
